name: Deploy

on:
  push:
    branches:
      - deploy-lara
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19' # Use your preferred Node version

      - name: Install dependencies
        run: npm install

      - name: Start the server (if applicable)
        run: npm start &
        env:
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_DATABASE: ${{ secrets.DATABASE_DATABASE }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          
      - name: Wait for server to be ready
        run: sleep 10 
          
      - name: Check server health
        run: curl http://localhost:3000
  
