name: Deploy

on:
  push:
    branches:
      - deploy-lara
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use your preferred Node version

      - name: Check the current directory
        run: pwd 

      - name: List the files in the current directory
        run: ls

      - name: Navigate to project directory
        run: cd backend
      
      - name: Install dependencies
        run: |
          ls
          pwd
          cd backend
          pwd
          npm install

      - name: Start the server (if applicable)
        run: |
          cd backend
          npm start &
        env:
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_DATABASE: ${{ secrets.DATABASE_DATABASE }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          nodemailer_email: ${{ secrets.nodemailer_email }}
          nodemailer_password: ${{ secrets.nodemailer_password }}
          PORT: ${{ secrets.PORT  }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }} }}


      - name: Wait for server to be ready
        run: sleep 10

      - name: Trigger Render Deployment
        env:
          LARA_RENDER_API_KEY: ${{ secrets.LARA_RENDER_API_KEY }} #used to get the service ID https://api-docs.render.com/reference/list-services
        run: |
          # Define the Render API endpoint and service ID
          SERVICE_ID=srv-cstjg9tumphs73fplo3g # Replace this with your actual Service ID
          RENDER_API_URL="https://api.render.com/v1/services/srv-cstjg9tumphs73fplo3g/deploys"
          # Trigger the deployment using Render's API
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            $RENDER_API_URL

      # - name: Check server health
      #   run: curl http://localhost:3000