name: DeployFrontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: 'gcr.io'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Remove previously built Docker image
        run: |
          docker image rm gcr.io/${{ secrets.GCP_PROJECT_ID }}/fullstack-bhatn-frontend:latest || true

      - name: Build Docker image
        run: |
          docker build \
            --platform linux/amd64 \
            --no-cache \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/fullstack-bhatn-frontend:latest \
            frontend \
            --push

      - name: Deploy to Cloud Run frontend
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: fullstack-bhatn-frontend
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/fullstack-bhatn-frontend:latest
          region: europe-west1
          platform: managed
          allow-unauthenticated: true
          timeout: 300s

      - name: Allow unauthenticated access
        run: |
          gcloud run services add-iam-policy-binding fullstack-bhatn-frontend \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --region=europe-west1 \
            --platform=managed