name: DeployBackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: 'gcr.io'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Remove previously built Docker image
        run: |
          docker image rm gcr.io/${{ secrets.GCP_PROJECT_ID }}/fullstack-bhatn:latest || true


      - name: Build Docker image
        run: |
          docker build \
            --platform linux/amd64 \
            --build-arg PORT=${{ secrets.PORT }} \
            --build-arg DB_HOST=${{ secrets.DB_HOST }} \
            --build-arg DB_NAME=${{ secrets.DB_NAME }} \
            --build-arg DB_USER=${{ secrets.DB_USER }} \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg DB_PORT=${{ secrets.DB_PORT }} \
            --no-cache \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/fullstack-bhatn:latest \
            backend \
            --push
            
            
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: fullstack-bhatn
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/fullstack-bhatn:latest
          region: europe-west1
          platform: managed
          allow-unauthenticated: true
          timeout: 300s

      - name: Allow unauthenticated access
        run: |
          gcloud run services add-iam-policy-binding fullstack-bhatn \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --region=europe-west1 \
            --platform=managed

      - name: Wait for server to be ready
        run: sleep 10